version: '2'
services:
  yolo:
    build: .
    ports:
      - "5000:5000"
    # volumes:
    #   - ./yolo:/yolo_app/yolo
    links:
      - mongodb
    container_name: yolo_api
    depends_on:
      - mongodb

  mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./database:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet
