version: '2'
services:
  yolo:
    build: .
    ports:
      - "5000:5000"
    environment:
      - IN_DOCKER=1
    links:
      - mongodb
    container_name: yolo_api
    depends_on:
      - mongodb

  mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
        volumes:
          - ./database:/data/db
        # ports:
        #     - 27017:27017
